-- Longrich Aqtobe: схема базы для Supabase
-- Запустить целиком: Supabase → SQL Editor → New query → вставить → Run.
-- ВАЖНО: в самом низу замените YOUR_EMAIL@example.com на email администратора.

-- ───────── Таблицы ─────────
create table if not exists public.products (
  id         bigint generated by default as identity primary key,
  name       text    not null check (char_length(name) between 1 and 200),
  category   text    not null default 'БАДы' check (char_length(category) <= 60),
  price      integer not null default 0 check (price >= 0),
  emoji      text    not null default '🌿',
  hidden     boolean not null default false,
  sort       integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key   text primary key,
  value text not null default ''
);

create table if not exists public.orders (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text check (char_length(name) <= 100),
  phone      text not null check (char_length(phone) between 10 and 25),
  comment    text check (char_length(comment) <= 500),
  items      jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) between 1 and 100),
  total      integer not null check (total >= 0),
  status     text not null default 'new' check (status in ('new', 'done', 'cancelled'))
);

create table if not exists public.admins (email text primary key);

-- ───────── Проверка «это администратор» ─────────
create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

-- ───────── Защита строк (RLS) ─────────
alter table public.products enable row level security;
alter table public.settings enable row level security;
alter table public.orders   enable row level security;
alter table public.admins   enable row level security;   -- без политик: клиент её не видит

-- Товары: все видят нескрытые, админ видит и правит всё
drop policy if exists "products read"  on public.products;
drop policy if exists "products admin" on public.products;
create policy "products read"  on public.products for select using (not hidden or public.is_admin());
create policy "products admin" on public.products for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Настройки (номер WhatsApp): читают все, правит админ
drop policy if exists "settings read"  on public.settings;
drop policy if exists "settings admin" on public.settings;
create policy "settings read"  on public.settings for select using (true);
create policy "settings admin" on public.settings for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Заказы: любой может создать новую заявку, читает и ведёт только админ
drop policy if exists "orders create" on public.orders;
drop policy if exists "orders admin"  on public.orders;
create policy "orders create" on public.orders for insert to anon, authenticated
  with check (status = 'new');
create policy "orders admin"  on public.orders for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- ───────── Права ─────────
grant usage on schema public to anon, authenticated;
grant select on public.products, public.settings to anon, authenticated;
grant insert on public.orders to anon, authenticated;
grant select, insert, update, delete on public.products, public.settings, public.orders to authenticated;
grant execute on function public.is_admin() to anon, authenticated;

-- ───────── Начальные данные ─────────
insert into public.settings (key, value) values ('whatsapp', '') on conflict (key) do nothing;

-- Администратор (замените email на свой!)
insert into public.admins (email) values ('YOUR_EMAIL@example.com') on conflict do nothing;

-- Товары (42 позиции из вашего каталога). Запускать один раз.
insert into public.products (name, category, price, emoji, sort) values
  ('Капсулы облепихового масла, 120 шт', 'БАДы', 32000, '🍊', 0),
  ('Кофе с кордицепсом, 10 саше', 'БАДы', 11500, '☕', 10),
  ('Пребиотик из соевого зародыша, 10 стиков', 'БАДы', 10500, '🌱', 20),
  ('Активные пробиотики, 20 пакетиков', 'БАДы', 5000, '🥛', 30),
  ('Кордицепс милитарис, 60 капсул', 'БАДы', 45000, '🍄', 40),
  ('Глюкозамин и хондроитин, 60 таблеток', 'БАДы', 18000, '🦴', 50),
  ('Витамин C жевательный, 60 таблеток', 'БАДы', 8000, '🍊', 60),
  ('NMN + CoQ10, 60 капсул', 'БАДы', 50000, '🧬', 70),
  ('Кальций/железо/цинк жевательные, 100 шт', 'БАДы', 7800, '🦷', 80),
  ('Натто и красный дрожжевой рис, 120 таблеток', 'БАДы', 25000, '💊', 90),
  ('Липазный комплекс, таблетированные конфеты', 'БАДы', 85000, '🍬', 100),
  ('Жидкий салат NFC (овощно-фруктовое пюре)', 'БАДы', 10000, '🥗', 110),
  ('Leopower «Сокровище силы», 160 капсул', 'БАДы', 85000, '💪', 120),
  ('Чай «Радостная лёгкость» (зелёный), 15 пакетиков', 'Чаи', 9500, '🍵', 130),
  ('Чай «Небесный дар» (коричневый), 15 пакетиков', 'Чаи', 9500, '🫖', 140),
  ('Чай «Изящная фигура» (розовый), 15 пакетиков', 'Чаи', 9500, '🌸', 150),
  ('Уходовая эссенция со змеиным жиром №1, 120 мл', 'Уход', 4000, '🧴', 160),
  ('Крем с лошадиным жиром, 500 г', 'Уход', 10000, '🐴', 170),
  ('Крем со змеиным жиром, 500 г', 'Уход', 12000, '🧴', 180),
  ('Эссенция с гиалуроновой кислотой, 220 мл', 'Уход', 12000, '💧', 190),
  ('Пептидный спрей-эссенция, 80 мл', 'Уход', 16000, '✨', 200),
  ('Набор с экстрактом граната (5 средств)', 'Уход', 150000, '🎁', 210),
  ('Набор Yacan Platinum (3 предмета)', 'Уход', 80000, '🎁', 220),
  ('Увлажняющий лосьон для тела, 165 мл', 'Уход', 3500, '🧴', 230),
  ('Гель для душа со змеиным желчем, 380 мл', 'Уход', 7000, '🚿', 240),
  ('Травяной гель для душа, 300 мл', 'Уход', 10000, '🌿', 250),
  ('Шампунь 2-в-1, 300 мл', 'Уход', 6000, '💆', 260),
  ('Роликовый дезодорант-антиперспирант, 50 мл', 'Уход', 5000, '🧼', 270),
  ('Мыло с бамбуковым углём', 'Уход', 5000, '🧼', 280),
  ('Антибактериальный набор «Цветочный эликсир»', 'Гигиена', 30000, '🌺', 290),
  ('Средство для интимной гигиены «Двойная свежесть», 248 мл', 'Гигиена', 8000, '🌸', 300),
  ('Набор гигиенических прокладок (ночные)', 'Гигиена', 80000, '🩷', 310),
  ('Спрей для свежести дыхания, 15 г', 'Гигиена', 4000, '🌬️', 320),
  ('Детская зубная щётка C101', 'Зубы', 2200, '🪥', 330),
  ('Детская зубная паста, 60 г', 'Зубы', 3000, '🍓', 340),
  ('Зубная щётка глубокого очищения', 'Зубы', 1000, '🪥', 350),
  ('Зубная паста с белым чаем', 'Зубы', 5000, '🦷', 360),
  ('Гостиничный набор, 5 предметов', 'Зубы', 1600, '🧳', 370),
  ('Жидкое средство для стирки, 1 л', 'Дом', 4500, '🧺', 380),
  ('Средство для мытья посуды, 1 л', 'Дом', 7000, '🍽️', 390),
  ('Кастрюля «Хэхэ Каннэн», 28 см', 'Дом', 250000, '🍲', 400),
  ('Энергетический π-стакан, 400 мл', 'Дом', 46000, '🥤', 410);
